# fly.toml app configuration file generated for sys-my-fin on 2023-06-08T13:29:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sys-my-fin"
primary_region = "gig"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
  BP_GO_TARGET= "./cmd/web"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
